---
title: "N2/-80 stocks Cryozoo"
output:
  pdf_document: default
  html_notebook: default
---



```{r}
library(readxl)
library(tidyverse)
read_excel_allsheets <- function(filename, skip=0, tibble = FALSE) {
  # I prefer straight data.frames
  # but if you like tidyverse tibbles (the default with read_excel)
  # then just pass tibble = TRUE
  sheets <- readxl::excel_sheets(filename)[-skip]
  x <- lapply(sheets, function(X) readxl::read_excel(filename, sheet = X))
  if(!tibble) x <- lapply(x, as.data.frame)
  names(x) <- make.names(sheets)
  x
}

path<-here::here()

```


```{r}
Nitrogen_and_80 <- read_excel_allsheets(filename=paste0(path,"/data/Nitrogen and -80.xlsx"),
                                        skip = c(1))
rm(cryo_long)
# i="BOX1_N2_RACK2"

fibro_bio<-names(Nitrogen_and_80)[c(1:13,18:28)]

  for (i in names(Nitrogen_and_80)[names(Nitrogen_and_80)%in%fibro_bio]){
  print(i)
    colnames(Nitrogen_and_80[[i]])[1]<-"row"
    if (!exists("cryo_long")){
    cryo_long<-Nitrogen_and_80[[i]] %>%
      filter(!is.na(row)) %>%
      mutate(across(everything(),as.character))%>% 
      pivot_longer(cols = 2:11,names_to = "column",values_to = "cryotube") %>% 
      mutate(box=i) 
    } else {
    cryo_long<-bind_rows(cryo_long,
                Nitrogen_and_80[[i]] %>%
      filter(!is.na(row)) %>% 
      mutate(across(everything(),as.character)) %>% 
      pivot_longer(cols = 2:11,names_to = "column",values_to = "cryotube") %>% 
      mutate(box=i)
      )
    }
}
  

head(cryo_long)

cryo_long<-cryo_long %>% 
  mutate(column=as.numeric(str_extract(column,"\\d+"))) %>% 
  mutate(row=as.numeric(str_extract(row,"\\d+"))) %>% 
  mutate(type=if_else(str_detect(box,"N2"),"N2","-80")) %>% 
  mutate(animal_ID=str_extract(cryotube,pattern = "[Aa]\\d+")) %>% 
  mutate(passage=str_extract(cryotube,pattern = "[Pp]\\d+")) %>%
  mutate(type2=case_when(str_detect(box,"(?i)iPSC")~"iPSC",
                        str_detect(box,"Fib")~"Fibroblast",
                        str_detect(box,"(?i)Bio")~"Biopsy",
                        .default ="other")) %>% 
  mutate(type2=case_when(type2=="other"& str_detect(cryotube,"(?i)Bio")~"Biopsy",
                         type2=="other"& str_detect(cryotube,"(?i)pbmc")~"PBMC",
                         type2=="other"& str_detect(cryotube,"(?i)pmbc")~"PBMC",
                         type2=="other"& str_detect(cryotube,"(?i)ipsc")~"iPSC",
                         type2=="other"& str_detect(cryotube,"(?i)fibro")~"Fibroblast",
                         T~type2)) %>% 
  mutate(type2=if_else(type2=="other"& !is.na(passage),"Fibroblast",type2)) %>% 
  mutate(info=str_remove(cryotube,pattern=animal_ID)) %>% 
  mutate(info=if_else(is.na(passage),info,str_remove(info,pattern=passage))) %>% 
  mutate(passage=as.numeric(str_remove(passage,pattern = "[Pp]")))%>% 
  mutate(passage=if_else(is.na(passage)& type2 %in% c("Biopsy","other"),-1, passage)) %>% 
  mutate(passage=if_else(is.na(passage)& type2=="PBMC",0, passage)) %>% 
  mutate(passage=if_else(is.na(passage)& type2=="Fibroblast",0, passage)) %>% 
  filter(!is.na(cryotube))


table(cryo_long$box,cryo_long$type2)


cryo_summary<-cryo_long %>% 
  filter(!is.na(animal_ID)) %>% 
  group_by(animal_ID,type2) %>% 
  summarize(n_passages=length(unique(passage)),max_passage=max(passage)) 
  
cryo_summary<-cryo_long %>% 
  filter(!is.na(animal_ID)) %>% 
  group_by(animal_ID,type2,passage) %>% 
  summarize(CT_per_passage=n()) %>% 
  pivot_wider(id_cols = c(animal_ID,type2),names_from = passage,values_from = CT_per_passage,values_fill = 0) %>% 
  ungroup() %>% 
  mutate(CT_total=rowSums(across(3:11))) %>% 
  left_join(cryo_summary)
  


saveRDS(cryo_long,paste0(path,"/data/Cryo_stocks_long.rds"))
saveRDS(cryo_summary,paste0(path,"/data/Cryo_stocks_summary.rds"))
```


```{r}

ggplot(cryo_long)+
  geom_bar(aes(box,fill=type2))+
  facet_grid(type~.,scales = "free",space = "free")+
  coord_flip()

ggplot(cryo_long)+
  geom_bar(aes(type,fill=type2))+
  coord_flip()

cryo_long %>% 
  filter(box=="BOX1_N2_RACK2") %>% 

ggplot()+
  geom_raster(aes(column,row,fill=type2))+
  geom_hline(yintercept = 0.5:10.5)+
  geom_vline(xintercept = 0.5:10.5)+
  scale_y_reverse(breaks=1:10)+
  scale_x_continuous(breaks=1:12,position = "top")+
  geom_text(aes(column,row,label=animal_ID))


ggplot(cryo_long)+
  geom_bar(aes(passage,fill=type2))+
  xlim(NA,20)


cryo_long %>% 
  filter(type2!="Biopsy") %>% 
ggplot()+
  geom_bar(aes(animal_ID,fill=factor(passage)))+
  ylim(NA,20)+
  theme(axis.text.x = element_text(angle=90,vjust=0.2))
```

