---
title: "Cryozoo - Mammal tree 2"
output:
  html_document:
    df_print: paged
  html_notebook: default
  pdf_document: default
editor_options: 
  chunk_output_type: console
---

```{r}
##
library(tidyverse)
library(cowplot)
library(treedataverse)
library(magrittr)
library(RColorBrewer)

## plotting options
theme_set(theme_bw())


here::here()

path<-here::here()

```


## Binninda-Emonds

match with tree annotation (tip.lables)
```{r}
# Mammalian supertree fron Binninda Edmonds et al. 2007
library(ggtree)

mammaltree<-read.tree(paste0(path,"/data/mammaltree.txt"))

mammaltree$tip.label[1:10]
```


# sort cryozoo samples by tree data
```{r}
summary_species<-readRDS(paste0(path,"/output/Species_List_with_genome_and_cl_info.rds")) %>%
  filter(class=="Mammalia") %>% 
  mutate(selected=if_else(cat=="Both","selected","FALSE")) %>% 
  mutate(orders_num=as.integer(as.factor(order)))

summary_species$tree_BE<-summary_species$scientific_name_%in%mammaltree$tip.label

table(summary_species$tree_BE)

summary_species[!(summary_species$scientific_name_%in%mammaltree$tip.label),"scientific_name_"]

summary_species %<>%  
  mutate(alternative_name=if_else(is.na(alternative_name),specie_name_cites,alternative_name),
         specie_name_cites2=specie_name_cites,
         specie_name_cites=if_else(tree_BE,specie_name_cites,alternative_name),
         alternative_name=if_else(tree_BE,alternative_name,specie_name_cites2),
         scientific_name_=gsub(specie_name_cites,pattern = " ",replacement = "_"))

summary_species$tree_BE<-summary_species$scientific_name_%in%mammaltree$tip.label

table(summary_species$tree_BE)

summary_species[!(summary_species$scientific_name_%in%mammaltree$tip.label),"scientific_name_"]

#Lets drop those species for now

selection_tree<-drop.tip(mammaltree, mammaltree$tip.label[!mammaltree$tip.label %in%
                                                      summary_species$scientific_name_ ])

selection_cryozoo<-summary_species[summary_species$scientific_name_%in%
                                      selection_tree$tip.label,]

selection_cryozoo<-selection_cryozoo[match(selection_tree$tip.label,selection_cryozoo$scientific_name_),]
pos<-which(colnames(selection_cryozoo)=="scientific_name_")
selection_cryozoo<-selection_cryozoo[,c(pos,1:(pos-1),(pos+1):ncol(selection_cryozoo))]

table(selection_tree$tip.label==selection_cryozoo$scientific_name_)

```


```{r}
tree<-ggtree(selection_tree, color="grey60", lwd=0.5)

selection_cryozoo %>% mutate(cat=factor(cat,levels=rev(c("No Genome\n No Fibro","Fibro","Genome","Both"))))

cols<-colorRampPalette(brewer.pal("RdPu",n = 9)[-c(1:3)])(length(unique(selection_cryozoo$order)))

tree<-tree %<+% selection_cryozoo+
  geom_tippoint(aes(color=order), size=2)+
  scale_colour_manual(values = cols)


tree

select_tree_ord<-tree$data[which(tree$data$isTip),]

desiredOrder  <- select_tree_ord[order(select_tree_ord$y),]$label

selection_cryozoo$sort_order<-match(selection_cryozoo$scientific_name_, desiredOrder)
selection_cryozoo<-arrange(selection_cryozoo,sort_order)


```

### Combine with cryozoo metadata

```{r}
### plot number of samples

available_bar<-ggplot(selection_cryozoo)+
  geom_col(aes(y=reorder(scientific_name_,sort_order),x=fibro,fill=order))+
  theme_void()+
  #scale_size_continuous(breaks = seq(from=0, to =12,by=2))+
  theme(plot.margin = unit(c(0, 0, 0,0), "cm"))+
  theme(legend.position = "none")



plot_grid(nrow=1,tree,
                 available_bar,
                 rel_widths = c(0.5,0.15),align = "hv",axis = "tb")

# ggsave(plot_grid(nrow=1,select_tree,
#                  available_bar,
#                  fibro_point,
#                  rel_widths = c(0.5,0.15,0.15)),
#        filename = "availability_tree.pdf",
#        path="C:/Users/Lucas/Desktop/",
#        device = "pdf",
#        width = 240,
#        height = 400,
#        units = "mm",
#        
#       )

```


###  Add heatmap to tree
```{r}


# tree<-ggtree(selection_tree, layout="circular", lwd=0.5)
# 
# tree<-tree %<+% selection_cryozoo+
#   geom_tippoint(aes(color=order), size=2)

rownames(selection_cryozoo)<-NULL

selection_cryozoo[duplicated(selection_cryozoo$scientific_name_),]

 mat_sel<-selection_cryozoo %>% 
   ungroup() %>% 
   filter(!(duplicated(scientific_name_))) %>% 
   mutate(fibro=fibro_l,
          replicates=samples>1) %>% 
   dplyr::select(scientific_name_,fibro,genome,replicates,selected) %>%
   column_to_rownames("scientific_name_") %>% 
   as.matrix
 

heatmap.colours <- c("purple","darkblue","grey75")

names(heatmap.colours) <- c("selected","TRUE","FALSE")

 tree_map<-gheatmap(tree,mat_sel, width=.2, offset=2, colnames=T,legend_title = "",
          colnames_position = "top",colnames_angle = 90,colnames_offset_y = 6,font.size = 4)   +
   scale_fill_manual(values=heatmap.colours,
                     na.value = "grey75",limits=force)+
   ylim(NA,90)+
   labs(colour="",fill="",shape="")+
   theme(legend.position = c(0.2,0.7))+
   theme(legend.direction = "vertical")+
   theme(legend.text = element_text(size=7))+
   guides(fill=guide_legend(order = 2,reverse = -1),colour="none")
   
tree_map

```


### MamPhy supertree (vertlife)
```{r}
big_tree<-drop.tip(read.nexus(paste0(path,"/data/MamPhy_fullPosterior_BDvr_DNAonly_4098sp_topoFree_NDexp_MCC_v2_target.tre")),"_Anolis_carolinensis")

summary_species<-readRDS(paste0(path,"/output/Species_List_with_genome_and_cl_info.rds")) %>%
  filter(class=="Mammalia") %>% 
  mutate(selected=if_else(cat=="Both","selected","FALSE")) %>% 
  mutate(orders_num=as.integer(as.factor(order)))

tree_meta <- data.frame(label=big_tree$tip.label) %>%
  separate(col = label,sep = "_",into = c("s1","s2","family","order"),remove = F) %>%
  unite(c(s1,s2),col = "scientific_name_",sep = "_") %>%
  mutate(family=str_to_title(family),
         order=str_to_title(order))

table(summary_species$scientific_name_ %in% tree_meta$scientific_name_)
```


```{r}

summary_species[!(summary_species$scientific_name_ %in% tree_meta$scientific_name_),]

summary_species$tree_MD<-summary_species$scientific_name_%in%tree_meta$scientific_name_

table(summary_species$tree_MD)

summary_species %<>%
  mutate(specie_name_cites=if_else(tree_MD,specie_name_cites,alternative_name),
         scientific_name_=gsub(specie_name_cites,pattern = " ",replacement = "_"))

summary_species$tree_MD<-summary_species$scientific_name_%in%tree_meta$scientific_name_

table(summary_species$tree_MD)

summary_species[!(summary_species$scientific_name_%in%tree_meta$scientific_name_),]
```

# Subset tree

```{r}

remove<-!(tree_meta$scientific_name_ %in% summary_species$scientific_name_)

table(remove)

big_tree<-drop.tip(big_tree,tree_meta$label[remove])

ggtree(big_tree)

```


## plot the tree
```{r}

tree_meta <- data.frame(label=big_tree$tip.label) %>%
  separate(col = label,sep = "_",into = c("s1","s2","family","order"),remove = F) %>%
  unite(c(s1,s2),col = "scientific_name_",sep = "_") %>%
  mutate(family=str_to_title(family),
         order=str_to_title(order))

big_tree$tip.label<-tree_meta$scientific_name_

summary_species<-summary_species[na.omit(match(big_tree$tip.label,summary_species$scientific_name_)),]

pos<-which(colnames(summary_species)=="scientific_name_")
summary_species<-summary_species[,c(pos,1:(pos-1),(pos+1):ncol(summary_species))]


p.tree<-ggtree(big_tree,color="grey60",lwd=0.5)

cols<-colorRampPalette(brewer.pal("RdPu",n = 9)[-c(1:3)])(length(unique(summary_species$order)))


p.tree2<-p.tree %<+% summary_species+
  geom_tippoint(aes(color=order), size=2)+
  guides(color="none")+
  scale_color_manual(values=cols)
p.tree2

```

```{r}
mat_sel2<-summary_species %>% 
   ungroup() %>% 
   filter(!(duplicated(scientific_name_))) %>% 
   mutate(fibro=fibro_l,
          replicates=samples>1) %>% 
   dplyr::select(scientific_name_,fibro,genome,replicates,selected) %>%
   column_to_rownames("scientific_name_") %>% 
   as.matrix
 

heatmap.colours <- c("purple","darkblue","grey75")

names(heatmap.colours) <- c("selected","TRUE","FALSE")

 tree_map2<-gheatmap(p.tree2,mat_sel2, width=.2, colnames=T,legend_title = "",
          colnames_position = "top",font.size = 4,colnames_angle =90,colnames_offset_y = 7,offset = 2)   +
   scale_fill_manual(values=heatmap.colours,
                     #breaks=c("Chromosome","Contig","Scaffold",2,4,6,8,10),
                     na.value = "grey75",limits=force)+
   ylim(NA,110)+
   labs(colour="",fill="",shape="")+
   theme(legend.position = c(0.4,0.9))+
   theme(legend.direction = "horizontal")+
   guides(fill="none",colour="none")
   
tree_map2


```

