---
title: "Finding closest reference genome"
output: html_notebook
---

For species where no reference genome exists we would like to find the closest reference genome. We can do this iteratively and then compare the distance between the original species and the reference genome species

```{r,message=F,warning=F}

library(tidyverse)
library(cowplot)
library(readxl)
library(runner)

theme_set(theme_classic())

here::here()

path<-here::here()

```


```{r}

GOAT_info <- read_delim(paste0(path,"/data/GenomeOnATree_Vertebrata1.tsv"), 
    delim = "\t", escape_double = FALSE, 
    col_types = cols(taxon_id = col_character()), 
    trim_ws = TRUE) %>% 
  mutate(common_name=str_replace_all(common_name, c('\\[\"'="",'\"\\]'=""))) %>% 
  mutate(synonym=str_replace_all(synonym, c('\\[\"'="",'\"\\]'=""))) %>% 
  mutate(tol_id=str_replace_all(tol_id, c('\\[\"'="",'\"\\]'=""))) %>% 
  filter(!is.na(assembly_level))


genus_level<-readRDS(paste0(path,"/output/Species_List_with_genome_and_cl_info.rds")) %>% 
  filter(is.na(assembly_level)) %>% 
  filter(class%in%c("Mammalia","Birds")) %>% 
  select(scientific_name,genus) %>% 
  left_join(GOAT_info,by="genus") %>% 
  mutate(assembly_level_num=case_when(assembly_level=="Chromosome"~4,
                                  assembly_level=="Scaffold"~3,
                                  assembly_level=="Contig"~2,
                                  T==assembly_level~1) 
                                  ) %>% 
  group_by(scientific_name.x) %>% 
  slice_max(assembly_level_num,n=1)  %>% 
  mutate(genome_taxlevel="genus")

family_level<-readRDS(paste0(path,"/output/Species_List_with_genome_and_cl_info.rds")) %>% 
  filter(is.na(assembly_level)) %>%
  filter(class%in%c("Mammalia","Birds")) %>% 
  filter(scientific_name%in%genus_level[is.na(genus_level$assembly_level_num),]$scientific_name.x) %>% 
  select(scientific_name,family) %>% 
  left_join(GOAT_info,by="family") %>% 
  mutate(assembly_level_num=case_when(assembly_level=="Chromosome"~4,
                                  assembly_level=="Scaffold"~3,
                                  assembly_level=="Contig"~2,
                                  T==assembly_level~1)
                                  ) %>% 
  group_by(scientific_name.x) %>% 
  slice_max(assembly_level_num,n=1) %>% 
  mutate(genome_taxlevel="family") 


summary_genomes<-bind_rows(genus_level%>%
            filter(!is.na(assembly_level_num)) %>% 
  dplyr::summarize(ngenomes=lengthunique(scientific_name.y),level=unique(assembly_level),genome_taxlevel=unique(genome_taxlevel)),

family_level%>%
            filter(!is.na(assembly_level_num)) %>% 
  dplyr::summarize(ngenomes=lengthunique(scientific_name.y),level=unique(assembly_level),genome_taxlevel=unique(genome_taxlevel))
) 

table(summary_genomes$level,summary_genomes$genome_taxlevel)
  
```

