---
title: "Plotting the Cryozoo"
output:
  html_document:
    df_print: paged
editor_options: 
  chunk_output_type: inline
---

```{r,message=F,warning=F}


library(tidyverse)
library(cowplot)
library(readxl)

theme_set(theme_classic())

here::here()

path<-here::here()

```


```{r}
List_of_species<-readRDS(paste0(path,"/output/Species_List_with_genome_and_cl_info.rds"))

List_of_species <- List_of_species %>% 
  mutate(cell_line=factor(cell_line, levels = c("No cell line","Fibro/PBMc","PBMc","Fibro"))) %>% 
  mutate(class=factor(class,levels=rev(c("Mammalia","Amphibia","Reptil","Aves")))) %>% 
  mutate(fibro_l=grepl(x=cell_line,pattern = "Fibro"),
         fibro_l=if_else(!(fibro_l)&fibro>0,T,fibro_l)) %>% 
  group_by(order) %>% 
  mutate(nspecies=n()) %>% 
  arrange(class,nspecies)

table(List_of_species$fibro_l)

sum_list<-List_of_species %>% 
  group_by(class) %>% 
  summarize(nspecies=n())

sum(sum_list$nspecies)

### colours

class_col<-ggsci::pal_aaas()(length(unique(List_of_species$class)))
names(class_col)<-unique(List_of_species$class)

```


```{r, fig.dim=c(8,7)}
bar.all_spec<-ggplot(data=List_of_species)+
  geom_bar(aes(x="All\n Samples",fill=class))+
  geom_text(data=sum_list,aes(label=nspecies),x="All\n Samples",y=c(150,102,93,50),color="white")+
  labs(x="",y="Number of species",fill="")+
  coord_flip()+
  theme_minimal()+
  theme(legend.position = "top",
        axis.ticks.y=element_blank(),
        axis.line.y = element_blank())+
  scale_fill_manual(values=class_col,limits=force)



bar.fibro<-ggplot(data=List_of_species)+
  geom_bar(aes(x=class,fill=class,alpha=fibro_l))+
  labs(x="",y="Number of species",fill="",alpha="Fibroblasts?")+
  coord_flip()+
  ggsci::scale_fill_aaas()+
  theme_minimal()+
  theme(legend.position = c(0.9,0.5),
        axis.ticks.y=element_blank(),
        axis.line.y = element_blank())+
  guides(fill="none")+
  scale_fill_manual(values=class_col,limits=force)


plot_grid(bar.all_spec,bar.fibro,nrow = 2,rel_heights = c(0.3,0.7),align = "v",axis="tblr")


```


```{r,fig.dim=c(10,12)}

ggplot(data=List_of_species)+
  geom_bar(aes(x=samples,fill=class),position = position_dodge(),show.legend = F)+
  labs(x="Number of samples",y="Number of species",fill="")+
  facet_grid(class~.)+
  scale_fill_manual(values=class_col,limits=force)+
  scale_x_continuous(breaks=c(1:9))+
  theme_bw()


```
```{r}

List_of_species %>% 
  mutate(samples_cat=case_when(samples==1~ "one",
                               samples==2~ "two",
                               samples>2 ~ "greater two")) %>% 
  mutate(samples_cat=factor(samples_cat,levels=rev(c("greater two","two","one")))) %>% 
  ggplot()+
  geom_bar(aes(class,fill=samples_cat),position=position_fill())+
  coord_flip()+
  scale_fill_viridis_d(alpha = 0.9,direction = -1)+
  scale_y_continuous(labels = scales::label_percent())+
  labs(y="percent of species",x="",fill="Samples per species")

```

# Only Fibroblast cell lines:

### Based on species table
```{r}
List_of_cell_lines<-List_of_species %>% 
  filter(fibro_l) %>% 
  group_by(order) %>% 
  mutate(nspecies=n()) %>% 
  ungroup() %>% 
  arrange(nspecies)

order_col <- scales::hue_pal()(length(unique(List_of_cell_lines$order)))
names(order_col)<-unique(List_of_cell_lines$order)


p.species_per_order<-ggplot(List_of_cell_lines)+
  geom_bar(aes(y=reorder(order,nspecies),fill=order),show.legend = F)+
  labs(y="",x="Number of species")+
  scale_x_reverse()+
  theme(axis.text.y=element_blank(),
        axis.ticks.y=element_blank(),
        axis.line.y = element_blank())+
  scale_fill_manual(values=order_col,limits=force)+
  facet_grid(class~.,scales = "free",space="free")


p.sample_per_species<-ggplot(List_of_cell_lines)+
  stat_summary(fun.data = "mean_se",aes(x=samples,y=reorder(order,nspecies)),colour="grey75")+
  ggbeeswarm::geom_quasirandom(aes(x=samples,y=reorder(order,nspecies),colour=order),groupOnX = F,show.legend = F)+
  labs(y="",x="Number of samples")+
  scale_x_continuous(breaks=1:9)+
  scale_colour_manual(values=order_col,limits=force)+
  facet_grid(class~.,scales = "free",space="free")


plot_grid(p.species_per_order,p.sample_per_species,rel_widths = c(0.45,0.55))

```




```{r}
List_of_species<-List_of_species %>% 
  mutate(genome=!is.na(assembly_level)) %>% 
  mutate(cat=case_when(genome & !(fibro_l) ~ "Genome",
                       !(genome) & !(fibro_l) ~ "No Genome\n No Fibro",
                       !(genome) & fibro_l ~ "Fibro",
                       genome & fibro_l ~ "Both")) %>% 
  mutate(cat=factor(cat,levels=c("No Genome\n No Fibro", "Fibro","Genome","Both")),
         cat_num=as.numeric(cat)/4,
         class=factor(class,levels=c("Mammalia","Aves","Reptil","Amphibia"))
         )

ggplot(List_of_species)+
  geom_bar(aes(fill=class,alpha=genome,x=class),position=position_fill())+
  coord_flip()+
  labs(y="percent of species with genome",x= "")+
  ggsci::scale_fill_aaas()+
  scale_y_continuous(labels = scales::label_percent())+
  theme_bw()+
  guides(fill="none")


ggplot(List_of_species)+
  geom_bar(aes(fill=class,alpha=genome,x=class))+
  coord_flip()+
  labs(y="Number of Species with genome",x= "")+
  ggsci::scale_fill_aaas()+
  theme_bw()+
  guides(fill="none")
```


```{r}
ggplot(List_of_species)+
  geom_bar(aes(x=class,fill=cat,alpha=cat_num))+
  coord_flip()+
  labs(y="Number of Species",x= "",
       fill= "group")+
  ggsci::scale_fill_npg()+
  theme_bw()+
  guides(alpha="none")

table(List_of_species$cat,List_of_species$class)
```


```{r}
selection<-List_of_species %>% 
  filter(cat=="Both") %>% 
  mutate(to_process=if_else(fibro>1,2,as.double(fibro))) %>% 
  group_by(order) %>% 
  mutate(nspecies=n(),
         order2=if_else(nspecies>2,order,"Other"))


sum(selection$to_process)

selection %>% 
  pivot_longer(cols=c(scaffold_n50,contig_n50), names_to="metric",values_to = "value") %>% 
ggplot()+
  geom_boxplot(aes(x=class,y=value),col="grey75",outlier.shape = NA)+
  ggbeeswarm::geom_beeswarm(aes(x=class,y=value,col=assembly_level),show.legend = T,groupOnX = T,dodge.width = 0.5)+
  facet_wrap(.~metric)+
  theme_bw()+
  theme(axis.text.x = element_text(angle=45,hjust=1))+
  scale_y_log10()+
  labs(x="")
```
```{r}
selection %>% 
group_by(class) %>% 
  mutate(med_g_size=median(genome_size)) %>% 
ggplot()+
  geom_boxplot(aes(x=class,y=genome_size),col="grey75",outlier.shape = NA)+
  ggbeeswarm::geom_beeswarm(aes(x=class,y=genome_size,col=class),
                            show.legend = T)+
  geom_label(aes(x=class,y=2*10^9,label=scales::scientific(med_g_size,2),colour=class),show.legend = F)+
  theme_bw()+
  theme(axis.text.x = element_text(angle=45,hjust=1))+
  scale_y_log10()+
  labs(x="")+
  scale_fill_manual(values=class_col,limits=force)
```

Genome size between Mammals and Birds differs by a factor of ~ 2.3. for Chip-seq this might mean we need 2.3 times the number of cells for the same amount of chromatin input into the IP.


```{r}
ggplot(selection) +
  geom_bar(aes(x=order,fill=order),show.legend = F)+
  facet_grid(class~.,scales = "free_y")+
  coord_flip()+
  labs(y="Number of Species")+
  scale_fill_manual(values=order_col)
```

Save data

```{r}
saveRDS(List_of_species,paste0(path,"/output/Species_List_with_genome_and_cl_info.rds"))

saveRDS(selection,paste0(path,"/output/Selected_species.rds"))

write_excel_csv2(filter(List_of_species,class=="Aves") %>% 
  ungroup() %>% 
  select(specie_name_cites),paste0(path,"/output/bird_names.csv"))


```
