---
title: "5.1 Cryozoo - trees"
output:
  html_document:
    df_print: paged
  html_notebook: default
  pdf_document: default
editor_options: 
  chunk_output_type: console
---

```{r}
##
library(tidyverse)
library(cowplot)
library(treedataverse)
library(magrittr)
library(RColorBrewer)
library(readxl)
library(googlesheets4)

## plotting options
theme_set(theme_bw())


here::here()

#path<-here::here()

path<-here::here()

```


### MamPhy supertree (vertlife)
```{r}
big_tree<-drop.tip(read.nexus(paste0(path,"/data/MamPhy_fullPosterior_BDvr_DNAonly_4098sp_topoFree_NDexp_MCC_v2_target.tre")),"_Anolis_carolinensis")

summary_species<-readRDS(paste0(path,"/output/Species_List_with_genome_and_cl_info2.rds")) %>%
  filter(class=="Mammalia") %>% 
  filter(!duplicated(species)) %>% 
  mutate(cryo_sample=case_when(cell_line=="Fibro/PBMc"~"Fibroblast and PBMc",
                               cell_line=="Fibro"~"Fibroblast",
                               cell_line=="PBMc"~"PBMc",
                               cell_line=="No cell line"~"Biopsy")
)

species_selection<- read_sheet(
  "https://docs.google.com/spreadsheets/d/1k-0sFR4AuaA0hAM2qeUZ8IMvLx96vY2JIQbwrNQtLj0/edit?usp=drive_link"
) %>%
  arrange(-silencer, -illumina, species) %>%
  select(silencer, illumina, species)
  

summary_species<-summary_species %>% left_join(species_selection) 

tree_meta <- data.frame(label=big_tree$tip.label) %>%
  separate(col = label,sep = "_",into = c("s1","s2","family","order"),remove = F) %>%
  unite(c(s1,s2),col = "species_",sep = "_") %>%
  mutate(family=str_to_title(family),
         order=str_to_title(order))

table(summary_species$species_ %in% tree_meta$species_)
```

# replace incorrect species names in tree
```{r}

summary_species[!(summary_species$species_ %in% tree_meta$species_),]

summary_species$tree_MD<-summary_species$species_%in%tree_meta$species_

table(summary_species$tree_MD)

# replace incorrect species names in tree
Wrong_Species_names2 <- read_excel(paste0(path,"/data/Wrong_Species_names2.xlsx"))%>% 
  filter(superclass=="Mammals")

tree_meta[tree_meta$species_ %in% Wrong_Species_names2$mammal_tree_name, ]$species_ <-
  Wrong_Species_names2$species_name_

summary_species$tree_MD<-summary_species$species_%in%tree_meta$species_

table(summary_species$tree_MD)

#replace incorect species names in species list
summary_species %<>%
  mutate(species=if_else(tree_MD,species,alternative_name),
         species_=gsub(species,pattern = " ",replacement = "_"))

summary_species$tree_MD<-summary_species$species_%in%tree_meta$species_

table(summary_species$tree_MD)

summary_species[!(summary_species$species_%in%tree_meta$species_),]
```



## plot the full tree
```{r}


big_tree$tip.label<-tree_meta$species_

summary_species2<-summary_species %>% 
  select(-c(family,order)) %>% 
  inner_join(tree_meta,by="species_") %>% 
  select(-label)



pos<-which(colnames(summary_species2)=="species_")
summary_species2<-summary_species2[,c(pos,1:(pos-1),(pos+1):ncol(summary_species2))]

table(duplicated(summary_species2$species_))

p.tree<-ggtree(big_tree,color="grey60",lwd=0.5,layout="circular")

cols<-colorRampPalette(ggsci::pal_futurama()(12))(length(unique(summary_species2$order)))
names(cols)<-unique(summary_species2$order)

#cols[!(names(cols)%in%summary_species$order)]<-"grey75"
                    

p.tree2<-p.tree %<+% summary_species2+
  geom_tippoint(aes(color=order, shape=cat))+
  scale_colour_manual(values=cols,na.value=NA)
p.tree2

```

# group OTUs to annotate which edges belong ot one oder, family etc.

```{r}
#the groups must be supplied as a list of the tip labels

groupInfo<-tree_meta %>% 
  select(order,species_) %>%
  pivot_wider(names_from = "order",values_from = "species_") %>% 
  as.list() %>% 
  list_flatten()


tree <-groupOTU(big_tree,groupInfo)

#as.tibble(tree) %>% view

cols<-c("grey75",colorRampPalette(ggsci::pal_futurama()(12))(length(names(groupInfo))+1))

names(cols)<-c("0",names(groupInfo))

# library(scales)
# 
# show_col(cols)

p.tree<-ggtree(tree,aes(color=group),lwd=0.5,layout = "circular")+
  scale_color_manual(values=cols,na.value = NA)

p.tree %<+% summary_species2+
  geom_tippoint(aes(shape=cat),color="grey25")

# p.tree %<+% summary_species2
# 
# dat<-select(column_to_rownames(summary_species2,var="species_"),cat)
# 
# gheatmap(p.tree,data = dat)
```

## subset for 1 species per family

```{r}

tree_meta2<-tree_meta %>% 
  group_by(family) %>% 
  slice_head(n=1) %>% 
  ungroup() %>% 
  filter(!(family%in%summary_species$family))

tree_meta_fam<-bind_rows(tree_meta2,subset(tree_meta,species_ %in% summary_species$species_))

summary_species2<-summary_species %>% 
  full_join(tree_meta_fam) %>% 
  mutate(order=if_else(order=="Cetartiodactyla","Artiodactyla",order)) %>% 
  select(-label)

## remove other species
remove <-
  !(tree_meta$species_ %in% summary_species2$species_)

table(remove)

sub_tree2 <- drop.tip(big_tree, tree_meta$species_[remove])

groupInfo<-summary_species2 %>% 
  select(order,species_) %>%
  pivot_wider(names_from = "order",values_from = "species_") %>% 
  as.list() %>% 
  list_flatten()


sub_tree2 <-groupOTU(sub_tree2,groupInfo)


cols<-c("grey75",colorRampPalette(ggsci::pal_futurama()(12))(length(names(groupInfo))+1))

names(cols)<-c("0",names(groupInfo))


keep <-
  (tree_meta$species_ %in% summary_species2$species_)

tree_meta3 <- tree_meta[keep, ]


```


## Plot the tree
```{r}
table(sub_tree2$tip.label == tree_meta3$species_)

sub_tree2$tip.label[!(sub_tree2$tip.label %in% summary_species2$species_)]

summary_species2 <-summary_species2[na.omit(match(sub_tree2$tip.label, summary_species2$species_)), ]

pos <- which(colnames(summary_species2) == "species_")

summary_species2 <-
  summary_species2[, c(pos, 1:(pos - 1), (pos + 1):ncol(summary_species2))]

saveRDS(sub_tree2,paste0(path,"/data/mamaltree_object_allfamilies.Rds"))
saveRDS(summary_species2,paste0(path,"/data/mamaltree_object_allfamilies_metadata.Rds"))
saveRDS(cols,paste0(path,"/data/mamaltree_object_allfamilies_cols.Rds"))
```


```{r}
p.tree3 <- ggtree(sub_tree2, aes(color = group), lwd = 0.5,mrsd = "01/08/2023",layout = "circular")


p.tree4 <- p.tree3 %<+% summary_species2 +
  geom_tippoint(aes(shape=cryo_sample), size = 3,color="grey55") +
  scale_color_manual(values=cols,na.value = NA)
p.tree4
```



### Plot rectangular and add matrix
```{r}

p.tree5 <- ggtree(sub_tree2, aes(color = group), lwd = 0.5,mrsd = "01/08/2023",layout = "rectangular")

mat_sel2<-summary_species2 %>% 
   ungroup() %>% 
   filter(!(duplicated(species_))) %>% 
   mutate(fibroblasts=fibro_l,
          replicates=individuals>1) %>% 
   dplyr::select(species_,fibroblasts,genome,replicates,annotation,cryo_sample) %>%
   column_to_rownames("species_") %>% 
   as.matrix
 

heatmap.colours <- c("darkblue","grey75","red","purple","darkgreen","orange")

names(heatmap.colours) <- c("TRUE","FALSE","Fibroblast","Fibroblast and PBMc","PBMc","Biopsy")


 tree_map2<-gheatmap(p.tree5,mat_sel2, width=.05, colnames=T,legend_title = "",
          colnames_position = "top",font.size = 3,colnames_angle =90,colnames_offset_y = 10,offset = 2)   +
   scale_fill_manual(values=heatmap.colours,
                     #breaks=c("Chromosome","Contig","Scaffold",2,4,6,8,10),
                     na.value = "grey75",limits=force)+
   scale_color_manual(values=cols)+
   ylim(NA,260)+
   labs(colour="",fill="",shape="")+
   theme(legend.direction = "horizontal")+
   #guides(fill="none")+
   theme_tree2()+
   theme(legend.position = c(0.3,0.7))
   
tree_map2

gc()
```

## only cryozoo species

```{r}

## remove other species
remove <-
  !(tree_meta$species_ %in% summary_species$species_)

table(remove)

sub_tree3 <- drop.tip(big_tree, tree_meta$species_[remove])

groupInfo<-summary_species %>% 
  select(order,species_) %>%
  pivot_wider(names_from = "order",values_from = "species_") %>% 
  as.list() %>% 
  list_flatten()


sub_tree3 <-groupOTU(sub_tree3,groupInfo)


cols<-c("grey75",colorRampPalette(ggsci::pal_futurama()(12))(length(names(groupInfo))+1))

names(cols)<-c("0",names(groupInfo))


keep <-
  (tree_meta$species_ %in% summary_species$species_)

tree_meta3 <- tree_meta[keep, ]

```

### plot subtree for cryozoo species
```{r}
table(sub_tree3$tip.label == tree_meta3$species_)

sub_tree3$tip.label[!(sub_tree3$tip.label %in% summary_species$species_)]

summary_species2 <-summary_species[na.omit(match(sub_tree2$tip.label, summary_species$species_)), ]

pos <- which(colnames(summary_species2) == "species_")

summary_species2 <-
  summary_species2[, c(pos, 1:(pos - 1), (pos + 1):ncol(summary_species2))]

p.tree3 <- ggtree(sub_tree3, aes(color = group), lwd = 0.5,mrsd = "01/08/2023",layout = "circular")



p.tree4 <- p.tree3 %<+% summary_species2 +
  geom_tippoint(aes(shape=cat), size = 2,color="grey55") +
  scale_color_manual(values=cols,na.value = NA)
p.tree4
```


#### rectangular layout and annotation
```{r}

p.tree5 <- ggtree(sub_tree3, aes(color = group), lwd = 0.5,mrsd = "01/08/2023",layout = "rectangular")

mat_sel2<-summary_species2 %>% 
   ungroup() %>% 
   filter(!(duplicated(species_))) %>% 
   mutate(fibroblasts=fibro_l,
          replicates=individuals>1,
          illumina=if_else(illumina,"illumina","FALSE"),
          silencer=if_else(silencer,"silencer","FALSE")) %>% 
   dplyr::select(species_,fibroblasts,genome,replicates,illumina,silencer) %>%
   column_to_rownames("species_") %>% 
   as.matrix
 

heatmap.colours <- c("purple","darkblue","grey75","red")

names(heatmap.colours) <- c("illumina","TRUE","FALSE","silencer")


 tree_map2<-gheatmap(p.tree5,mat_sel2, width=.1, colnames=T,legend_title = "",
          colnames_position = "top",font.size = 3,colnames_angle =90,colnames_offset_y = 8,offset = 2)   +
   scale_fill_manual(values=heatmap.colours,
                     #breaks=c("Chromosome","Contig","Scaffold",2,4,6,8,10),
                     na.value = "grey75",limits=force)+
   scale_color_manual(values=cols)+
   ylim(NA,120)+
   labs(colour="",fill="",shape="")+
   theme(legend.direction = "horizontal")+
   guides(fill="none")+
   theme_tree2()+
   theme(legend.position = c(0.3,0.7))
   
tree_map2


save_plot(plot = tree_map2,base_height =6,base_width = 10,filename = paste0(path,"/output/selection_tree_all.png"))

gc()
```

