---
title: "Cell Culture"
output: html_notebook
---

Here the tables summarizing growth of different cell lines are summarized 


```{r}
library(googlesheets4)
library(tidyverse)
library(purrr)

theme_set(theme_minimal())

path<-"/Users/lucas/Library/CloudStorage/GoogleDrive-lucasesteban.wange@upf.edu/My Drive/Projects/Cryozoo/1.Species_selection/"

read_gsheet_allsheets2 <- function(filename, skip=1, pattern="", tibble = FALSE) {
  if (pattern==""){
  sheets <- googlesheets4::sheet_names(filename)[-skip]
  } else {
  sheets <- googlesheets4::sheet_names(filename)[-skip]  
  sheets<-sheets[which(grepl(sheets,pattern=pattern))]
  }
  x <- lapply(sheets, function(X) googlesheets4::read_sheet(filename, sheet = X))
  if(!tibble) x <- lapply(x, as.data.frame)
  names(x) <- make.names(sheets)
  x
}
```

## Collect information about harvesting from Albert and Sebas's working sheet

```{r}
cell_culture_illumina<-read_gsheet_allsheets2("https://docs.google.com/spreadsheets/d/1JdEs_1eV47Es7Mz6YIU9AjJNC2vKxgIQ9XDNnZNhJJ8/edit?usp=sharing",
                                      pattern="*Thaw*",
                                      tibble = T)

# Bind all tables and add sheet name
cell_culture_illumina_df <-imap_dfr(cell_culture_illumina, ~ mutate(.x, sheet = .y) %>% 
                              mutate(`Cryotube Passage`=as.character(`Cryotube Passage`)))


cell_culture_illumina_df<-cell_culture_illumina_df %>% 
  janitor::clean_names() %>% 
  mutate(cryotube_passage=as.numeric(str_remove(cryotube_passage,pattern = "[p,P]"))) %>% 
  filter(!is.na(cryotube_passage)) %>% 
  select(-species,-x10,-x11) 

write_sheet(cell_culture_illumina_df,"https://docs.google.com/spreadsheets/d/1vyBZwssG8ndUcGmDg4kLEPwOJJk15bOrXztO876HCOs/edit?usp=sharing",
            "cell_culture_illumina")
```


```{r}
harvest3<-cell_culture_illumina_df %>% 
  rename(animal_id=id_axxx,thawing_date=date_thawed,passage=cryotube_passage,
         cultured_in=status,cell_number=pellet,need_stock=stock_needed)

# %>%
#   select(-superclass) %>% 
#   left_join(select(all_samples,c(animal_id,species,superclass,project))) %>% 
#   rename(group=project)
  
```



```{r}
harvesting <- read_sheet(
  "https://docs.google.com/spreadsheets/d/1vyBZwssG8ndUcGmDg4kLEPwOJJk15bOrXztO876HCOs/edit?usp=sharing",
  "tracking_silencer",
  col_types = "nccccncccclDlDnccccnlllnnnDc"
) %>%  filter(!is.na(animal_id)) %>%
  select(-order) %>%
  bind_rows(
    read_sheet(
      "https://docs.google.com/spreadsheets/d/1vyBZwssG8ndUcGmDg4kLEPwOJJk15bOrXztO876HCOs/edit?usp=sharing",
      "tracking_all_illumina",
      col_types = "nccccncccclDlDnccccnlllnnnDc"
    ) %>%
      select(-order)
  ) %>% filter(!is.na(animal_id)) %>%
  mutate(Harvested = if_else(is.na(Harvested), F, Harvested)) %>%
  mutate(Thawed = if_else(is.na(Thawed), F, Thawed)) %>% 
  janitor::clean_names()


write_sheet(harvesting,ss = "https://docs.google.com/spreadsheets/d/1vyBZwssG8ndUcGmDg4kLEPwOJJk15bOrXztO876HCOs/edit?usp=sharing",sheet = "cell_culture_phase1")
```


```{r}

all_harvest<-bind_rows(harvesting,harvest3) %>% 
  mutate(thawing_date=if_else(is.na(thawing_date)&!is.na(cultured_in),as.Date(1990-11-08),thawing_date)) %>% 
  mutate(thawed=!is.na(thawing_date)) %>% 
  filter(!is.na(cultured_in))

saveRDS(all_harvest,paste0(path,"/output/cell_culture_summary.rds"))

```
