---
title: "Extractions"
output:
  html_document:
    df_print: paged
---


```{r}
library(tidyverse)
library(readxl)
library(googlesheets4)

path<-here::here()
```


```{r}

rna_ex<-read_sheet("https://docs.google.com/spreadsheets/d/1SRid9RGRfcCpGAWsAXG8h0wE-7p1fhOtwvkMJgR1s8w/edit?usp=sharing","RNA Extractions",col_types = "c")[,1:18] %>% 
  mutate(animal_id=str_extract(`Cryozoo number`,"A\\d+")) %>% 
  select(-`Cryozoo number`)

```

```{r}

dna_ex<-read_sheet("https://docs.google.com/spreadsheets/d/1SRid9RGRfcCpGAWsAXG8h0wE-7p1fhOtwvkMJgR1s8w/edit?usp=sharing","DNA extractions",col_types = "c")[,2:18] %>% 
  rename(animal_id=animal_ID) %>% 
  janitor::clean_names()


dna_ex %>% 
  mutate(tissue_or_cells=if_else(is.na(tissue_or_cells),"uncertain",tissue_or_cells)) %>% 
  pivot_longer(cols = c(nucleic_acid_nanodrop_ng_ul,concentration_qubit_br_ng_ul),names_to = "measurment_type",values_to = "concentration") %>% 
  mutate(concentration=as.numeric(str_replace(concentration,",","."))) %>% 
  group_by(animal_id,tissue_or_cells) %>% 
  summarize(extracted=sum(concentration,na.rm = TRUE)>1)
  

```


# Extraction locations

```{r}

extr_long<-readRDS(paste0(path,"/data/Extractions_long.rds"))

```

