---
title: "Update Sample table"
output: html_notebook
---


This script updates the sample table with information about sequencing,nucleic acid extractions and cryotubes
```{r,message=F,warning=F}


library(tidyverse)
library(cowplot)
library(readxl)
library(googlesheets4)

theme_set(theme_classic())

here::here()

path<-here::here()


```

# Species and sample tables

```{r}

Species_list_complete<-readRDS(paste0(path,"/output/Species_List_with_genome_and_cl_info.rds"))
Samples_complete<-readRDS(paste0(path,"/output/Sample_List_all_species_clean.rds"))

```



# Cryotubes

```{r}
cryo_long<-readRDS(paste0(path,"/data/Cryo_stocks_long.rds"))
cryo_summary<-readRDS(paste0(path,"/data/Cryo_stocks_summary.rds"))
```


## Add info about cryotubes to Sample table
```{r}

cryotubes_per_type<-cryo_summary %>% 
  select(animal_id,type2,CT_total,max_passage,n_passages) %>% 
  filter(!is.na(n_passages)) %>% 
  filter(type2!="other") %>% 
  pivot_wider(names_from = type2,values_from = c(CT_total,max_passage,n_passages)) %>% 
  select(-max_passage_Biopsy) 


```


# Sequencing data

```{r}

cryozoo_seq<-read_sheet("https://docs.google.com/spreadsheets/d/1YI-0bB7OFfjaUM4af9Lv3BAd1X0x9CoCTKZN3BQM4KA/edit?usp=sharing",
                        sheet = "All_Sequenced") 

```
## cryozoo_seq_wide
```{r}
cryozoo_seq_l <- cryozoo_seq %>% 
  mutate(status2=case_when(status%in% "sequenced" & qc_result=="Ok"~ "sequenced",
                           status%in% "sequenced" & qc_result!="Ok"~ "qc_fail",
                           status%in%c("extracted","tech_rep","repeat","ready to process","ready", "pending")~"pending",
                           T~status)) %>% 
  mutate(status2=factor(status2,levels=c("sequenced","submitted","pending","qc_fail"))) %>% 
  select(any_of(c("animal_id", "species", "type","status2","cnag_id"))) %>% 
  group_by(animal_id, species, type) %>% 
  slice_min(status2,with_ties = F) 

cryozoo_seq_w <- cryozoo_seq_l %>% 
  mutate(cnag_id_status=if_else(status2=="qc_fail",paste0(cnag_id," (",status2,")"),cnag_id)) %>% 
  select(cnag_id_status,type,animal_id) %>% 
  pivot_wider(id_cols = c(animal_id),names_from = type,values_from = cnag_id_status)

```

# Cell culture

```{r}

all_harvest<-readRDS(paste0(path,"/output/cell_culture_summary.rds")) 
  

```


```{r}
#Samples_complete<-
  Samples_complete %>% 
  left_join(cryotubes_per_type) %>% 
  left_join(cryozoo_seq_w) %>% 
  left_join(select(all_harvest,animal_id,thawed,harvested,days_to_harvest,outcome)) %>% view

```

## per species table
```{r}
# cryozoo_seq_sp_num <- cryozoo_seq_w %>%
#   ungroup() %>% 
#   select(-animal_id) %>%  # Remove animal_id before grouping
#   group_by(species) %>%   # Group by species (or others, as needed)
#   summarize(across(everything(), ~ sum(!is.na(.))), .groups = "drop")

cryozoo_seq_w_sp <- cryozoo_seq %>% 
  mutate(status2=case_when(status%in%c("sequenced")~ "sequenced",
                           status%in%c("extracted","tech_rep","repeat","ready to process","ready", "pending")~"pending",
                           T~status)) %>% 
  mutate(status2=factor(status2,levels=c("sequenced","submitted","pending"))) %>% 
  select(any_of(c( "species", "type","status2"))) %>% 
  group_by(species, type) %>% 
  slice_min(status2,with_ties = F) %>% 
  pivot_wider(names_from = type, values_from = status2)


```

